__title__ = 'copperhead'
__description__ = 'An Inline C++ Extension Generator for Python.'
__url__ = 'https://github.com/Lnk2past/copperhead'
__version__ = '2019.5.0'
__author__ = 'Lnk2past'
__license__ = 'MIT'
