dist: xenial
language: python
python:
  - "3.6"
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"
before_install:
  - chmod +x .ci/travis/*
addons:
  apt:
    update: true
install:
  - python setup.py install
script:
  - .ci/travis/run_tests.sh